version: "3"
services:
  api:
    build: .
    environment:
      - OGRE_DB_USERNAME=ogre
      - OGRE_DB_PASSWORD=supersecurepassword
      - OGRE_DB_HOSTNAME=db
      - OGRE_DB_NAME=ogre
    ports:
      - "3736:3736"
    networks:
      - ogre
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: "mariadb:latest"
    volumes:
      - db-data:/var/lib/mysql/data
    networks:
      - ogre
    environment:
      - MYSQL_DATABASE=ogre
      - MYSQL_USER=ogre
      - MYSQL_USER_PASSWORD=supersecurepassword
      - MYSQL_ROOT_PASSWORD=securerootpassword
    restart: unless-stopped

volumes:
  db-data:

networks:
  ogre: