# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/amtgard/ogre
    steps:
      - checkout
      - run: go build
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t amtgard/ogre:$TAG -t amtgard/ogre:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push amtgard/ogre:$TAG
          docker push amtgard/ogre:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
